import { Theme } from '@material-ui/core/styles/createMuiTheme';
import React from 'react';

export type Procedure = (...args: any[]) => void;

export const AppTitle: (prefix: string, suffix: string) => React.FunctionComponent;
export const ButtonWithLoading: any;
export const ConfirmationDialog: any;
export const ErrorBoundary: any;
export const GlobalSnackbar: any;
export const UnoSuspense: any;
export const LoadingIcon: any;
export const TextValidator: any;
export const Title: React.FunctionComponent;
export const asyncOnEnterKey: any;
export const colorGenerator: any;
export const createFetchController: any;
export const debounce: any;
export const enhanceWithClickOutside: any;
export const humanize: (name: string) => string;
export const isNotAllBlanks: any;
export const maxNaturalNumber: any;
export const onEnterKey: any;
export const requestController: any;
export const useEffectWithLoading: any;
export const useNow: any;
export const usePersistedState: any;
export const useStateForField: any;
export const useStateForModel: any;
export const useStateForModelWithLoading: any;
export const useToggle: (defaultValue: any) => any;
export const useToggleStateForField: (defaultValue: any) => any;
export const UnoTheme: Theme;